# Generated by Django 2.0.5 on 2018-10-02 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionInState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissal_date', models.DateField(verbose_name='Дата прийняття')),
                ('order_date', models.DateField(verbose_name='Дата наказу')),
                ('order_number', models.CharField(max_length=40, verbose_name='№ наказу')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прийняття в штат',
                'verbose_name_plural': 'Прийняття в штат',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(verbose_name='Дата наказу')),
                ('order_number', models.CharField(max_length=40, verbose_name='№ наказу')),
                ('factory', models.CharField(max_length=40, verbose_name='Завод')),
                ('city', models.CharField(max_length=40, verbose_name='Місто відрядження')),
                ('start_on', models.DateField(verbose_name='Початок відрядження')),
                ('expire', models.DateField(verbose_name='Закінчення відрядження')),
                ('polish_border', models.DateField(verbose_name='Перетин кордону в Польщу')),
                ('ukrainian_border', models.DateField(verbose_name='Перетин кордону в Україну')),
                ('dismissal_reason', models.CharField(max_length=40, verbose_name='Дострокове закінчення')),
                ('dismissal_basis', models.CharField(max_length=40, verbose_name='Переривання відрядження')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Відрядження',
                'verbose_name_plural': 'Відрядження',
            },
        ),
        migrations.CreateModel(
            name='Dismissal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissal_date', models.DateField(verbose_name='Дата звільнення')),
                ('order_date', models.DateField(verbose_name='Дата наказу')),
                ('order_number', models.CharField(max_length=40, verbose_name='№ наказу')),
                ('dismissal_reason', models.CharField(max_length=40, verbose_name='Причина звільнення')),
                ('dismissal_basis', models.CharField(max_length=40, verbose_name='Підстава звільнення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Звільнення',
                'verbose_name_plural': 'Звільнення',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=40, verbose_name='Підприємство-роботодавець')),
                ('factory', models.CharField(max_length=40, verbose_name='Завод')),
                ('expire', models.DateField(verbose_name='Дата завершення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Дозвіл на роботу',
                'verbose_name_plural': 'Дозволи на роботу',
            },
        ),
        migrations.CreateModel(
            name='TransferInState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissal_date', models.DateField(verbose_name='Дата переведення')),
                ('order_date', models.DateField(verbose_name='Дата наказу')),
                ('order_number', models.CharField(max_length=40, verbose_name='№ наказу')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Переведення в штат',
                'verbose_name_plural': 'Переведення в штат',
            },
        ),
        migrations.CreateModel(
            name='Vnosok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=40, verbose_name='Підприємство-роботодавець')),
                ('factory', models.CharField(max_length=40, verbose_name='Завод')),
                ('position', models.CharField(max_length=40, verbose_name='Посада')),
                ('start_on', models.DateField(verbose_name='Дата подачі')),
                ('expire', models.DateField(verbose_name='Дата закриття')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вньосок',
                'verbose_name_plural': 'Вньоски',
            },
        ),
    ]
