# Generated by Django 2.0.5 on 2018-10-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='scan_copy',
            field=models.ImageField(blank=True, null=True, upload_to='user/permission', verbose_name='Скан дозволу'),
        ),
    ]
