# Generated by Django 2.0.5 on 2018-10-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20181002_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptioninstate',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата наказу'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='expire',
            field=models.DateField(blank=True, null=True, verbose_name='Закінчення відрядження'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата наказу'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='polish_border',
            field=models.DateField(blank=True, null=True, verbose_name='Перетин кордону в Польщу'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start_on',
            field=models.DateField(blank=True, null=True, verbose_name='Початок відрядження'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='ukrainian_border',
            field=models.DateField(blank=True, null=True, verbose_name='Перетин кордону в Україну'),
        ),
        migrations.AlterField(
            model_name='dismissal',
            name='dismissal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата звільнення'),
        ),
        migrations.AlterField(
            model_name='dismissal',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата наказу'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='expire',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершення'),
        ),
        migrations.AlterField(
            model_name='transferinstate',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата наказу'),
        ),
        migrations.AlterField(
            model_name='vnosok',
            name='expire',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закриття'),
        ),
        migrations.AlterField(
            model_name='vnosok',
            name='start_on',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подачі'),
        ),
        migrations.AlterField(
            model_name='vocation',
            name='expire',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закінчення відпустки'),
        ),
        migrations.AlterField(
            model_name='vocation',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата наказу'),
        ),
        migrations.AlterField(
            model_name='vocation',
            name='start_on',
            field=models.DateField(blank=True, null=True, verbose_name='Дата початку відпустки'),
        ),
    ]
