# Generated by Django 2.0.5 on 2018-10-25 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0005_auto_20181024_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingСontrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory', models.CharField(max_length=40, verbose_name='Завод')),
                ('expire', models.DateField(blank=True, null=True, verbose_name="Дата від'їзду")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_controls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вхідний контроль',
                'verbose_name_plural': 'Вхідні контролі',
            },
        ),
    ]
