# Generated by Django 2.0.5 on 2018-10-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_incomingсontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='dismissal_basis',
            field=models.CharField(max_length=400, verbose_name='Переривання відрядження'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='dismissal_reason',
            field=models.CharField(max_length=400, verbose_name='Дострокове закінчення'),
        ),
    ]
