# Generated by Django 2.0.5 on 2018-10-26 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_disappearance_prognosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dismissal',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to=settings.AUTH_USER_MODEL),
        ),
    ]
