# Generated by Django 2.0.5 on 2018-10-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_auto_20181026_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptioninstate',
            name='employer',
            field=models.CharField(default=1, max_length=40, verbose_name='Підприємство-роботодавець'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adoptioninstate',
            name='position',
            field=models.CharField(default=1, max_length=40, verbose_name='Посада'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='basis_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата наказу'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='basis_number',
            field=models.CharField(default=1, max_length=40, verbose_name='№ наказу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='reason_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата наказу'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='reason_number',
            field=models.CharField(default=1, max_length=40, verbose_name='№ наказу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='input_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подачі внеск'),
        ),
        migrations.AddField(
            model_name='permission',
            name='note',
            field=models.CharField(default=1, max_length=40, verbose_name='Примітки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='prediction_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата відправлення внеску'),
        ),
        migrations.AddField(
            model_name='permission',
            name='receiving_date',
            field=models.DateField(blank=True, null=True, verbose_name='Прогнозована дата отримання дозволу'),
        ),
        migrations.AddField(
            model_name='permission',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата початку'),
        ),
        migrations.AddField(
            model_name='permission',
            name='voivodship',
            field=models.CharField(default=1, max_length=40, verbose_name='Воєводство'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vocation',
            name='period',
            field=models.CharField(default=1, max_length=40, verbose_name='Період для відпустки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='dismissal_basis',
            field=models.CharField(max_length=200, verbose_name='Переривання відрядження'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='dismissal_reason',
            field=models.CharField(max_length=200, verbose_name='Дострокове закінчення'),
        ),
    ]
