# Generated by Django 2.0.5 on 2018-11-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_auto_20181030_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='basis_number',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='№ наказу'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='dismissal_basis',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Причина переривання відрядження'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='dismissal_reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Причина дострокове закінчення'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='reason_number',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='№ наказу'),
        ),
    ]
