# Generated by Django 2.0.5 on 2018-11-14 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0027_auto_20181114_0907'),
        ('work', '0012_auto_20181114_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferinstate',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.Position', verbose_name='Посада'),
        ),
    ]
