# Generated by Django 2.0.5 on 2018-11-14 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_transferinstate_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptioninstate',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.Position', verbose_name='Посада'),
        ),
    ]
