# Generated by Django 2.0.5 on 2018-11-15 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_auto_20181115_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasisList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Підстава звільнення')),
            ],
            options={
                'verbose_name': 'Підстава звільнення',
                'verbose_name_plural': 'Підстави звільнення',
            },
        ),
        migrations.AlterField(
            model_name='dismissal',
            name='dismissal_basis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='work.BasisList', verbose_name='Підстава звільнення'),
        ),
    ]
