# Generated by Django 2.0.5 on 2018-12-03 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0017_auto_20181116_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='pay_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплати'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='note',
            field=models.CharField(max_length=400, verbose_name='Примітки'),
        ),
        migrations.AlterField(
            model_name='prognosis',
            name='reason',
            field=models.CharField(max_length=400, verbose_name='Причина повернення'),
        ),
        migrations.AlterField(
            model_name='vnosok',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vnosok_list', to='work.Employer', verbose_name='Підприємство-роботодавець'),
        ),
        migrations.AlterField(
            model_name='vnosok',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vnosok_list', to='work.Factory', verbose_name='Завод'),
        ),
        migrations.AlterField(
            model_name='vnosok',
            name='position',
            field=models.CharField(max_length=60, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='vocation',
            name='comment',
            field=models.CharField(max_length=400, verbose_name='Примітки'),
        ),
        migrations.AlterField(
            model_name='vocation',
            name='period',
            field=models.CharField(max_length=60, verbose_name='Період для відпустки'),
        ),
    ]
