# Generated by Django 2.0.5 on 2018-12-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0019_auto_20181217_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptioninstate',
            name='order_number',
            field=models.CharField(blank=True, default=' ', max_length=20, verbose_name='№ наказу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='basis_number',
            field=models.CharField(blank=True, default=' ', max_length=40, verbose_name='№ наказу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='city',
            field=models.CharField(blank=True, default=' ', max_length=40, verbose_name='Місто відрядження'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='dismissal_basis',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Причина переривання відрядження'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='dismissal_reason',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Причина дострокове закінчення'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='order_number',
            field=models.CharField(blank=True, default=' ', max_length=40, verbose_name='№ наказу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='reason_number',
            field=models.CharField(blank=True, default=' ', max_length=40, verbose_name='№ наказу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dismissal',
            name='dismissal_reason',
            field=models.CharField(blank=True, default=' ', max_length=40, verbose_name='Причина звільнення'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dismissal',
            name='order_number',
            field=models.CharField(blank=True, default=' ', max_length=40, verbose_name='№ наказу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prognosis',
            name='reason',
            field=models.CharField(blank=True, default=' ', max_length=400, verbose_name='Причина повернення'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transferinstate',
            name='order_number',
            field=models.CharField(blank=True, default=' ', max_length=20, verbose_name='№ наказу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vocation',
            name='comment',
            field=models.CharField(blank=True, default=' ', max_length=400, verbose_name='Примітки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vocation',
            name='order_number',
            field=models.CharField(blank=True, default=' ', max_length=20, verbose_name='№ наказу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vocation',
            name='period',
            field=models.CharField(blank=True, default=' ', max_length=60, verbose_name='Період для відпустки'),
            preserve_default=False,
        ),
    ]
