# Generated by Django 2.0.5 on 2018-10-02 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dwelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40, verbose_name='Адреса проживання')),
                ('landlord_name', models.CharField(max_length=40, verbose_name="Ім'я орендодавця")),
                ('neighbor_name', models.CharField(max_length=40, verbose_name='ПІБ сусіда по кімнаті')),
                ('start_on', models.DateField(verbose_name='Дата заселення')),
                ('expire', models.DateField(verbose_name='Дата вивільнення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Місце проживання',
                'verbose_name_plural': 'Місця проживання',
            },
        ),
    ]
