# Generated by Django 2.0.5 on 2018-10-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwelling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwelling',
            name='expire',
            field=models.DateField(blank=True, null=True, verbose_name='Дата вивільнення'),
        ),
        migrations.AlterField(
            model_name='dwelling',
            name='start_on',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заселення'),
        ),
    ]
