# Generated by Django 2.0.5 on 2018-10-25 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dwelling', '0002_auto_20181003_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwelling',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Кінцева дата'),
        ),
        migrations.AlterField(
            model_name='dwelling',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dwelling', to=settings.AUTH_USER_MODEL),
        ),
    ]
