# Generated by Django 2.0.5 on 2018-10-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20181003_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ukrainianpassport',
            options={'verbose_name': 'Паспорт громадянина України', 'verbose_name_plural': 'Паспорти громадян України'},
        ),
        migrations.AlterField(
            model_name='foreignpassport',
            name='authority',
            field=models.CharField(max_length=100, verbose_name='Орган, що видав'),
        ),
    ]
