# Generated by Django 2.0.5 on 2018-10-22 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20181018_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignpassport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_pasport', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='militaryrecords',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalid',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ukrainianpassport',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pasports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visas', to=settings.AUTH_USER_MODEL),
        ),
    ]
