# Generated by Django 2.0.5 on 2018-10-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20181022_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='first_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подачі'),
        ),
        migrations.AddField(
            model_name='visa',
            name='prediction_date',
            field=models.DateField(blank=True, null=True, verbose_name='Прогнозована дата отримання'),
        ),
    ]
