# Generated by Django 2.0.5 on 2018-12-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20181031_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ukrainianpassport',
            name='number',
            field=models.CharField(max_length=40, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='ukrainianpassport',
            name='series',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Серія'),
        ),
    ]
