# Generated by Django 2.0.5 on 2018-12-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20181206_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignpassport',
            name='authority',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Орган, що видав'),
        ),
        migrations.AlterField(
            model_name='foreignpassport',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код держави'),
        ),
        migrations.AlterField(
            model_name='foreignpassport',
            name='number',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='foreignpassport',
            name='type',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='ukrainianpassport',
            name='number',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='ukrainianpassport',
            name='place_of_issue',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ким був виданий'),
        ),
    ]
