# Generated by Django 2.0.5 on 2018-12-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20181207_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignpassport',
            name='authority',
            field=models.CharField(blank=True, default=' ', max_length=100, verbose_name='Орган, що видав'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foreignpassport',
            name='country_code',
            field=models.CharField(blank=True, default=' ', max_length=10, verbose_name='Код держави'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foreignpassport',
            name='number',
            field=models.CharField(blank=True, default=' ', max_length=6, verbose_name='Номер паспорта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foreignpassport',
            name='type',
            field=models.CharField(blank=True, default=' ', max_length=1, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ukrainianpassport',
            name='number',
            field=models.CharField(blank=True, default=' ', max_length=40, verbose_name='Номер паспорта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ukrainianpassport',
            name='place_of_issue',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Ким був виданий'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ukrainianpassport',
            name='series',
            field=models.CharField(max_length=2, null=True, verbose_name='Серія'),
        ),
    ]
