# Generated by Django 2.0.5 on 2018-10-02 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=60, verbose_name='Сертифікуюча організація')),
                ('welding_position', models.CharField(max_length=60, verbose_name='Просторове положення')),
                ('thickness', models.CharField(max_length=60, verbose_name='Товщина')),
                ('start_on', models.DateField(verbose_name='Дата видачі')),
                ('expire', models.DateField(verbose_name='Дата завершення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сертифікат',
                'verbose_name_plural': 'Сертифікати',
            },
        ),
        migrations.CreateModel(
            name='WeldingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Метод зварювання',
                'verbose_name_plural': 'Методи зварювання',
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='welding_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate.WeldingType', verbose_name='Метод зварювання'),
        ),
    ]
