# Generated by Django 2.0.5 on 2018-10-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='expire',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершення'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='start_on',
            field=models.DateField(blank=True, null=True, verbose_name='Дата видачі'),
        ),
    ]
