# Generated by Django 2.0.5 on 2018-10-23 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificate', '0002_auto_20181003_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_on', models.DateField(blank=True, null=True, verbose_name='Дата співбесіди')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Співбесіда',
                'verbose_name_plural': 'Співбесіди',
            },
        ),
        migrations.CreateModel(
            name='InterviewType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Тип співбесіди')),
                ('result', models.CharField(max_length=40, verbose_name='Результат співбесіди')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_types', to='certificate.Interview')),
            ],
            options={
                'verbose_name': 'Тип співбесіди',
                'verbose_name_plural': 'Типи співбесіди',
            },
        ),
        migrations.CreateModel(
            name='Polish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solo', models.BooleanField(default=False, verbose_name='Вивчив сам')),
                ('course', models.BooleanField(default=False, verbose_name='Прослухав курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Польська мова',
                'verbose_name_plural': 'Польська мова',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_on', models.DateField(blank=True, null=True, verbose_name='Дата тестування')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тестування',
                'verbose_name_plural': 'Тестування',
            },
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Тип тестування')),
                ('result', models.CharField(max_length=40, verbose_name='Результат тестування')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_types', to='certificate.Test')),
            ],
            options={
                'verbose_name': 'Тип тестування',
                'verbose_name_plural': 'Типи тестування',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=40, verbose_name='Результат тренування')),
                ('start_on', models.DateField(blank=True, null=True, verbose_name='Дата початку тренування')),
                ('expire', models.DateField(blank=True, null=True, verbose_name='Дата завершення тренування')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тренування',
                'verbose_name_plural': 'Тренування',
            },
        ),
    ]
