# Generated by Django 2.0.5 on 2018-10-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_interview_interviewtype_polish_test_testtype_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewtype',
            name='result',
        ),
        migrations.RemoveField(
            model_name='testtype',
            name='result',
        ),
        migrations.AddField(
            model_name='interview',
            name='result',
            field=models.CharField(default=1, max_length=40, verbose_name='Результат співбесіди'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='result',
            field=models.CharField(default=1, max_length=40, verbose_name='Результат тестування'),
            preserve_default=False,
        ),
    ]
