# Generated by Django 2.0.5 on 2018-10-30 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0007_auto_20181030_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='certificate.InterviewType', verbose_name='Тип співбесіди'),
        ),
    ]
