# Generated by Django 2.0.5 on 2018-10-31 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0008_auto_20181030_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtype',
            name='interview',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certification_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата сертифікації'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='paying_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплати'),
        ),
        migrations.AddField(
            model_name='test',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='certificate.TestType'),
            preserve_default=False,
        ),
    ]
