# Generated by Django 2.0.5 on 2018-10-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0009_auto_20181031_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_scan',
            field=models.ImageField(blank=True, null=True, upload_to='user/certificates', verbose_name='Скан копія'),
        ),
    ]
