# Generated by Django 2.0.5 on 2018-11-14 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0010_certificate_certificate_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='certificate.TestType', verbose_name='Тип тестування'),
        ),
    ]
