# Generated by Django 2.0.5 on 2018-12-04 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificate', '0011_auto_20181114_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulgarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Вміння працювати болгаркою')),
            ],
            options={
                'verbose_name': 'Вміння працювати болгаркою',
                'verbose_name_plural': 'Вміння працювати болгаркою',
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Вміння працювати з газовим паяльником')),
            ],
            options={
                'verbose_name': 'Вміння працювати з газовим паяльником',
                'verbose_name_plural': 'Вміння працювати з газовим паяльником',
            },
        ),
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name="Тип з'єднання")),
            ],
            options={
                'verbose_name': "Тип з'єднання",
                'verbose_name_plural': "Типи з'єднання",
            },
        ),
        migrations.CreateModel(
            name='DrawReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Читання креслень')),
            ],
            options={
                'verbose_name': 'Читання креслень',
                'verbose_name_plural': 'Читання креслень',
            },
        ),
        migrations.CreateModel(
            name='MetalBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Марка металу')),
            ],
            options={
                'verbose_name': 'Марка металу',
                'verbose_name_plural': 'Марки металу',
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Оцінка кваліфікації')),
            ],
            options={
                'verbose_name': 'Інша спеціальність',
                'verbose_name_plural': 'Інші спеціальності',
            },
        ),
        migrations.CreateModel(
            name='PreQualificationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.CharField(max_length=300, verbose_name='Товщина')),
                ('bulgarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.Bulgarian', verbose_name='Вміння працювати болгаркою')),
                ('candle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.Candle', verbose_name='Вміння працювати з газовим паяльником')),
                ('connection_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.ConnectionType', verbose_name="Тип з'єднання")),
                ('draw_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.DrawReading', verbose_name='Читання креслень')),
                ('metal_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.MetalBrand', verbose_name='Марка металу')),
                ('other', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.Other', verbose_name='Оцінка кваліфікації')),
            ],
            options={
                'verbose_name': 'Попередня оцінка кваліфікації',
                'verbose_name_plural': 'Попередня оцінки кваліфікації',
            },
        ),
        migrations.CreateModel(
            name='QualificationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.CharField(max_length=300, verbose_name='Товщина')),
                ('bulgarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.Bulgarian', verbose_name='Вміння працювати болгаркою')),
                ('candle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.Candle', verbose_name='Вміння працювати з газовим паяльником')),
                ('connection_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.ConnectionType', verbose_name="Тип з'єднання")),
                ('draw_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.DrawReading', verbose_name='Читання креслень')),
                ('metal_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.MetalBrand', verbose_name='Марка металу')),
                ('other', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.Other', verbose_name='Оцінка кваліфікації')),
            ],
            options={
                'verbose_name': 'Оцінка кваліфікації',
                'verbose_name_plural': 'Оцінки кваліфікації',
            },
        ),
        migrations.CreateModel(
            name='SemiAutomatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Досвід зварювання напівавтоматом')),
            ],
            options={
                'verbose_name': 'Досвід зварювання напівавтоматом',
                'verbose_name_plural': 'Досвід зварювання напівавтоматом',
            },
        ),
        migrations.CreateModel(
            name='SpatialPosture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Просторове положення')),
            ],
            options={
                'verbose_name': 'Просторове положення',
                'verbose_name_plural': 'Просторові положення',
            },
        ),
        migrations.CreateModel(
            name='WeldMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Спосіб зварювання')),
            ],
            options={
                'verbose_name': 'Спосіб зварювання',
                'verbose_name_plural': 'Способи зварювання',
            },
        ),
        migrations.AddField(
            model_name='qualificationlevel',
            name='semiautomatic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.SemiAutomatic', verbose_name='Досвід зварювання напівавтоматом'),
        ),
        migrations.AddField(
            model_name='qualificationlevel',
            name='spatial_posture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.SpatialPosture', verbose_name='Просторове положення'),
        ),
        migrations.AddField(
            model_name='qualificationlevel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualificationlevel',
            name='welding_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.WeldMethod', verbose_name='Спосіб зварювання'),
        ),
        migrations.AddField(
            model_name='prequalificationlevel',
            name='semiautomatic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.SemiAutomatic', verbose_name='Досвід зварювання напівавтоматом'),
        ),
        migrations.AddField(
            model_name='prequalificationlevel',
            name='spatial_posture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.SpatialPosture', verbose_name='Просторове положення'),
        ),
        migrations.AddField(
            model_name='prequalificationlevel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_qualifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prequalificationlevel',
            name='welding_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.WeldMethod', verbose_name='Спосіб зварювання'),
        ),
    ]
