# Generated by Django 2.0.5 on 2018-12-05 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0013_auto_20181205_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postqualificationlevel',
            name='other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.Other', verbose_name='Рівень кваліфікації'),
        ),
    ]
