# Generated by Django 2.0.5 on 2018-12-07 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0014_auto_20181205_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='organization',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Сертифікуюча організація'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='thickness',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Товщина'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='welding_position',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Просторове положення'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='welding_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='certificate.WeldingType', verbose_name='Метод зварювання'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='result',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Результат співбесіди'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='certificate.InterviewType', verbose_name='Тип співбесіди'),
        ),
        migrations.AlterField(
            model_name='test',
            name='result',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Результат тестування'),
        ),
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='certificate.TestType', verbose_name='Тип тестування'),
        ),
        migrations.AlterField(
            model_name='training',
            name='result',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Результат тренування'),
        ),
    ]
