# Generated by Django 2.0.5 on 2018-12-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0015_auto_20181207_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='postqualificationlevel',
            name='specialization',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Спеціалізація'),
        ),
    ]
