# Generated by Django 2.0.5 on 2018-12-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0016_postqualificationlevel_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationlevel',
            name='specialization',
            field=models.CharField(blank=True, max_length=300, verbose_name='Спеціалізація'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='organization',
            field=models.CharField(blank=True, default=' ', max_length=60, verbose_name='Сертифікуюча організація'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='thickness',
            field=models.CharField(blank=True, default=' ', max_length=60, verbose_name='Товщина'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='welding_position',
            field=models.CharField(blank=True, default=' ', max_length=60, verbose_name='Просторове положення'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interview',
            name='result',
            field=models.CharField(blank=True, default=' ', max_length=40, verbose_name='Результат співбесіди'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postqualificationlevel',
            name='specialization',
            field=models.CharField(blank=True, default=' ', max_length=300, verbose_name='Спеціалізація'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='result',
            field=models.CharField(blank=True, default=' ', max_length=40, verbose_name='Результат тестування'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='training',
            name='result',
            field=models.CharField(blank=True, default=' ', max_length=40, verbose_name='Результат тренування'),
            preserve_default=False,
        ),
    ]
