# Generated by Django 2.0.5 on 2018-09-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20180912_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['sort'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AddField(
            model_name='contacttype',
            name='validate_string',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
