# Generated by Django 2.0.5 on 2018-09-17 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20180912_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='personal_id',
            field=models.SmallIntegerField(default=123, max_length=10, unique=True, verbose_name='Идентификационный код'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.CharField(max_length=20, verbose_name='Контакт'),
        ),
    ]
