# Generated by Django 2.0.5 on 2018-09-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20180917_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Логин'),
        ),
    ]
