# Generated by Django 2.0.5 on 2018-09-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20180925_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Посада')),
            ],
            options={
                'verbose_name': 'Посада',
                'verbose_name_plural': 'Посади',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_profile.Position', verbose_name='Посада'),
            preserve_default=False,
        ),
    ]
