# Generated by Django 2.0.5 on 2018-10-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_auto_20180925_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='personal_id',
        ),
    ]
