# Generated by Django 2.0.5 on 2018-10-05 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_auto_20181003_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacttype',
            name='validate_string',
        ),
    ]
