# Generated by Django 2.0.5 on 2018-10-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0021_auto_20181022_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адреса прописки'),
        ),
        migrations.AddField(
            model_name='user',
            name='residence_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фактична адреса'),
        ),
    ]
