# Generated by Django 2.0.5 on 2018-10-23 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0022_auto_20181022_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Мова')),
                ('level', models.CharField(max_length=40, verbose_name='Мови')),
            ],
            options={
                'verbose_name': 'Мова',
                'verbose_name_plural': 'Мови',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Примітки'),
        ),
        migrations.AddField(
            model_name='language',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to=settings.AUTH_USER_MODEL),
        ),
    ]
