# Generated by Django 2.0.5 on 2018-11-15 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0027_auto_20181114_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Рівень')),
            ],
            options={
                'verbose_name': 'Рівень володіння',
                'verbose_name_plural': 'Рівні володіння',
            },
        ),
        migrations.CreateModel(
            name='LanguageTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Мова')),
            ],
            options={
                'verbose_name': 'Мова',
                'verbose_name_plural': 'Мови',
            },
        ),
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='user_profile.LanguageLevel', verbose_name='Рівень'),
        ),
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='user_profile.LanguageTitle', verbose_name='Мова'),
        ),
    ]
