# Generated by Django 2.0.5 on 2018-11-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0028_auto_20181115_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(max_length=40, verbose_name='Рівень'),
        ),
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Мова'),
        ),
    ]
