# Generated by Django 2.0.5 on 2018-11-15 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0029_auto_20181115_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='user_profile.LanguageLevel', verbose_name='Рівень'),
        ),
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='user_profile.LanguageTitle', verbose_name='Мова'),
        ),
    ]
