# Generated by Django 2.0.5 on 2018-11-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0030_auto_20181115_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languagetitle',
            options={'verbose_name': 'Список мов', 'verbose_name_plural': 'Списки мов'},
        ),
    ]
