# Generated by Django 2.0.5 on 2018-11-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0031_auto_20181115_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttype',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Тип контакта'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=30, verbose_name='Статус'),
        ),
    ]
