# Generated by Django 2.0.5 on 2018-12-03 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0032_auto_20181115_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Тип контакта')),
            ],
            options={
                'verbose_name': 'Інтелект',
                'verbose_name_plural': 'Інтелект',
            },
        ),
        migrations.CreateModel(
            name='PersonalityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Тип контакта')),
            ],
            options={
                'verbose_name': 'Тип особистості',
                'verbose_name_plural': 'Типи особистості',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalismType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Тип контакта')),
            ],
            options={
                'verbose_name': 'Професіоналізм',
                'verbose_name_plural': 'Професіоналізм',
            },
        ),
        migrations.CreateModel(
            name='PsychologicalPortrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intelligence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.IntelligenceType', verbose_name='Інтелект')),
                ('personality_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.PersonalityType', verbose_name='Тип особистості')),
                ('professionalism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.ProfessionalismType', verbose_name='Професіоналізм')),
            ],
            options={
                'verbose_name': 'Психологічний портрет',
                'verbose_name_plural': 'Психологічні портрети',
            },
        ),
        migrations.CreateModel(
            name='SelfDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Тип контакта')),
            ],
            options={
                'verbose_name': 'Самодисципліна',
                'verbose_name_plural': 'Самодисципліна',
            },
        ),
        migrations.CreateModel(
            name='SociabilityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Тип контакта')),
            ],
            options={
                'verbose_name': 'Комунікабельність',
                'verbose_name_plural': 'Комунікабельність',
            },
        ),
        migrations.CreateModel(
            name='TemperamentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Тип контакта')),
            ],
            options={
                'verbose_name': 'Темперамент',
                'verbose_name_plural': 'Темперамент',
            },
        ),
        migrations.AddField(
            model_name='psychologicalportrait',
            name='self_discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.SelfDiscipline', verbose_name='Самодисципліна'),
        ),
        migrations.AddField(
            model_name='psychologicalportrait',
            name='sociability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.SociabilityType', verbose_name='Комунікабельність'),
        ),
        migrations.AddField(
            model_name='psychologicalportrait',
            name='temperament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.TemperamentType', verbose_name='Темперамент'),
        ),
        migrations.AddField(
            model_name='psychologicalportrait',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portraits', to=settings.AUTH_USER_MODEL),
        ),
    ]
