# Generated by Django 2.0.5 on 2018-12-03 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0033_auto_20181203_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selfdiscipline',
            options={'verbose_name': 'Самодисциплінованість', 'verbose_name_plural': 'Самодисциплінованість'},
        ),
        migrations.AlterField(
            model_name='intelligencetype',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Інтелект'),
        ),
        migrations.AlterField(
            model_name='personalitytype',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Тип особистості'),
        ),
        migrations.AlterField(
            model_name='professionalismtype',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Професіоналізм'),
        ),
        migrations.AlterField(
            model_name='psychologicalportrait',
            name='intelligence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.IntelligenceType', verbose_name='Інтелект'),
        ),
        migrations.AlterField(
            model_name='psychologicalportrait',
            name='personality_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.PersonalityType', verbose_name='Тип особистості'),
        ),
        migrations.AlterField(
            model_name='psychologicalportrait',
            name='professionalism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.ProfessionalismType', verbose_name='Професіоналізм'),
        ),
        migrations.AlterField(
            model_name='psychologicalportrait',
            name='self_discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.SelfDiscipline', verbose_name='Самодисципліна'),
        ),
        migrations.AlterField(
            model_name='psychologicalportrait',
            name='sociability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.SociabilityType', verbose_name='Комунікабельність'),
        ),
        migrations.AlterField(
            model_name='psychologicalportrait',
            name='temperament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.TemperamentType', verbose_name='Темперамент'),
        ),
        migrations.AlterField(
            model_name='selfdiscipline',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Самодисциплінованість'),
        ),
        migrations.AlterField(
            model_name='sociabilitytype',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Комунікабельність'),
        ),
        migrations.AlterField(
            model_name='temperamenttype',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Темперамент'),
        ),
    ]
