# Generated by Django 2.0.5 on 2018-12-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0034_auto_20181203_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Адреса прописки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='residence_address',
            field=models.CharField(blank=True, default=' ', max_length=200, verbose_name='Фактична адреса'),
            preserve_default=False,
        ),
    ]
