# Generated by Django 2.0.5 on 2018-09-25 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_organization', models.CharField(max_length=20, verbose_name='Страхова організація')),
                ('expire', models.DateField(blank=True, null=True, verbose_name='Дата завершення')),
            ],
            options={
                'verbose_name': 'Страхування',
                'verbose_name_plural': 'Страхування',
            },
        ),
        migrations.CreateModel(
            name='InsuranceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Страхова подія')),
                ('expire', models.DateField(blank=True, null=True, verbose_name='Дата завершення')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.Insurance')),
            ],
            options={
                'verbose_name': 'Страхова подія',
                'verbose_name_plural': 'Страхові події',
            },
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Тип страхування')),
            ],
            options={
                'verbose_name': 'Тип страхування',
                'verbose_name_plural': 'Типы страхування',
            },
        ),
        migrations.AddField(
            model_name='insurance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.InsuranceType', verbose_name='Тип страхування'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
