# Generated by Django 2.0.5 on 2018-09-25 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('early_expire', models.DateField(blank=True, null=True, verbose_name='Дострокове завершення')),
                ('has_review', models.BooleanField(default=False, verbose_name='Наявність медогляду')),
            ],
            options={
                'verbose_name': 'Медогляд',
                'verbose_name_plural': 'Медогляди',
            },
        ),
        migrations.CreateModel(
            name='MedicalReviewType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Тип медогляду')),
                ('expire', models.DateField(blank=True, null=True, verbose_name='Дата завершення')),
            ],
            options={
                'verbose_name': 'Тип медогляду',
                'verbose_name_plural': 'Типы медогляду',
            },
        ),
        migrations.AddField(
            model_name='medicalreview',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.MedicalReviewType', verbose_name='Тип медогляду'),
        ),
        migrations.AddField(
            model_name='medicalreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
