# Generated by Django 2.0.5 on 2018-10-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20180925_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='scan_copy',
            field=models.ImageField(blank=True, null=True, upload_to='user/insurance', verbose_name='Скан страхування'),
        ),
    ]
