# Generated by Django 2.0.5 on 2018-10-24 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_insurance_scan_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insuranceevent',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='medicine.Insurance'),
        ),
        migrations.AlterField(
            model_name='medicalreview',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicals', to='medicine.MedicalReviewType', verbose_name='Тип медогляду'),
        ),
        migrations.AlterField(
            model_name='medicalreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicals', to=settings.AUTH_USER_MODEL),
        ),
    ]
