# Generated by Django 2.0.5 on 2018-10-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_auto_20181024_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='start_on',
            field=models.DateField(blank=True, null=True, verbose_name='Дата початку'),
        ),
    ]
