# Generated by Django 2.0.5 on 2018-12-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_insurance_start_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='pay_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплати'),
        ),
    ]
