# Generated by Django 2.0.5 on 2018-10-02 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivilegesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Тип пільг')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Працівник')),
            ],
            options={
                'verbose_name': 'Тип пільг',
                'verbose_name_plural': 'Типы пільг',
            },
        ),
    ]
