# Generated by Django 2.0.5 on 2018-10-05 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('privileges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire', models.DateField(blank=True, null=True, verbose_name='Закінчення квоти')),
            ],
            options={
                'verbose_name': 'Квоти',
                'verbose_name_plural': 'Квоти',
            },
        ),
        migrations.CreateModel(
            name='QuotaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Тип квоти')),
                ('title', models.TextField(max_length=400, verbose_name='Опис квоти')),
            ],
            options={
                'verbose_name': 'Тип квоти',
                'verbose_name_plural': 'Типи квот',
            },
        ),
        migrations.AddField(
            model_name='quota',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='privileges.QuotaType', verbose_name='Тип квоти'),
        ),
        migrations.AddField(
            model_name='quota',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Працівник'),
        ),
    ]
