# Generated by Django 2.0.5 on 2018-11-14 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('privileges', '0002_auto_20181005_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qoutas', to='privileges.QuotaType', verbose_name='Тип квоти'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qoutas', to=settings.AUTH_USER_MODEL, verbose_name='Працівник'),
        ),
    ]
